// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ApiV1EndpointsAggregatorsListAggregatorsData,
  ApiV1EndpointsAggregatorsListAggregatorsGroupedData,
  ApiV1EndpointsAggregatorsListAggregatorsGroupedResponses,
  ApiV1EndpointsAggregatorsListAggregatorsResponses,
  ApiV1EndpointsArticlesDeleteArticleData,
  ApiV1EndpointsArticlesDeleteArticleResponses,
  ApiV1EndpointsArticlesGetArticleData,
  ApiV1EndpointsArticlesGetArticleResponses,
  ApiV1EndpointsArticlesListArticlesData,
  ApiV1EndpointsArticlesListArticlesResponses,
  ApiV1EndpointsArticlesMarkArticlesReadData,
  ApiV1EndpointsArticlesMarkArticlesReadResponses,
  ApiV1EndpointsArticlesMarkArticlesStarredData,
  ApiV1EndpointsArticlesMarkArticlesStarredResponses,
  ApiV1EndpointsArticlesReloadArticleData,
  ApiV1EndpointsArticlesReloadArticleResponses,
  ApiV1EndpointsAuthAuthStatusData,
  ApiV1EndpointsAuthAuthStatusResponses,
  ApiV1EndpointsAuthLoginUserData,
  ApiV1EndpointsAuthLoginUserResponses,
  ApiV1EndpointsAuthLogoutUserData,
  ApiV1EndpointsAuthLogoutUserResponses,
  ApiV1EndpointsFeedsClearFeedData,
  ApiV1EndpointsFeedsClearFeedResponses,
  ApiV1EndpointsFeedsCreateFeedData,
  ApiV1EndpointsFeedsCreateFeedResponses,
  ApiV1EndpointsFeedsDeleteFeedData,
  ApiV1EndpointsFeedsDeleteFeedResponses,
  ApiV1EndpointsFeedsGetFeedData,
  ApiV1EndpointsFeedsGetFeedResponses,
  ApiV1EndpointsFeedsListFeedsData,
  ApiV1EndpointsFeedsListFeedsResponses,
  ApiV1EndpointsFeedsReloadFeedData,
  ApiV1EndpointsFeedsReloadFeedResponses,
  ApiV1EndpointsFeedsUpdateFeedData,
  ApiV1EndpointsFeedsUpdateFeedResponses,
  ApiV1EndpointsStatisticsGetStatisticsData,
  ApiV1EndpointsStatisticsGetStatisticsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth Status
 *
 * Get current authentication status.
 *
 * Returns user information if authenticated, otherwise returns
 * authenticated=False.
 */
export const apiV1EndpointsAuthAuthStatus = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiV1EndpointsAuthAuthStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiV1EndpointsAuthAuthStatusResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/auth/status/",
    ...options,
  });

/**
 * Login User
 *
 * Authenticate user and create session.
 *
 * Args:
 * data: Login credentials (username and password)
 *
 * Returns:
 * LoginResponse with success status and user information
 */
export const apiV1EndpointsAuthLoginUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsAuthLoginUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsAuthLoginUserResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/auth/login/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout User
 *
 * Logout current user and destroy session.
 *
 * Returns:
 * Success message
 */
export const apiV1EndpointsAuthLogoutUser = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiV1EndpointsAuthLogoutUserData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ApiV1EndpointsAuthLogoutUserResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/auth/logout/",
    ...options,
  });

/**
 * List Feeds
 *
 * List all feeds with optional filtering and pagination.
 *
 * Args:
 * search: Search query for feed name
 * feed_type: Filter by feed type (article, youtube, podcast, reddit)
 * enabled: Filter by enabled status
 *
 * Returns:
 * Paginated list of feeds with article counts
 */
export const apiV1EndpointsFeedsListFeeds = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiV1EndpointsFeedsListFeedsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiV1EndpointsFeedsListFeedsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/",
    ...options,
  });

/**
 * Create Feed
 *
 * Create a new feed.
 *
 * Args:
 * data: Feed creation data
 *
 * Returns:
 * Created feed
 */
export const apiV1EndpointsFeedsCreateFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsCreateFeedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsFeedsCreateFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Feed
 *
 * Delete a feed and all its articles.
 *
 * Args:
 * feed_id: Feed ID
 *
 * Returns:
 * Success message
 */
export const apiV1EndpointsFeedsDeleteFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsDeleteFeedData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiV1EndpointsFeedsDeleteFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/",
    ...options,
  });

/**
 * Get Feed
 *
 * Get detailed information about a specific feed.
 *
 * Args:
 * feed_id: Feed ID
 *
 * Returns:
 * Detailed feed information including metadata
 */
export const apiV1EndpointsFeedsGetFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsGetFeedData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiV1EndpointsFeedsGetFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/",
    ...options,
  });

/**
 * Update Feed
 *
 * Update an existing feed.
 *
 * Args:
 * feed_id: Feed ID
 * data: Updated feed data
 *
 * Returns:
 * Updated feed
 */
export const apiV1EndpointsFeedsUpdateFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsUpdateFeedData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiV1EndpointsFeedsUpdateFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reload Feed
 *
 * Reload a feed (fetch new articles).
 *
 * Args:
 * feed_id: Feed ID
 * force: If True, force re-download of all articles
 *
 * Returns:
 * Reload statistics
 */
export const apiV1EndpointsFeedsReloadFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsReloadFeedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsFeedsReloadFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/reload/",
    ...options,
  });

/**
 * Clear Feed
 *
 * Clear all articles from a feed.
 *
 * Args:
 * feed_id: Feed ID
 *
 * Returns:
 * Success message
 */
export const apiV1EndpointsFeedsClearFeed = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsFeedsClearFeedData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsFeedsClearFeedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/clear/",
    ...options,
  });

/**
 * List Articles
 *
 * List articles from a specific feed.
 *
 * Args:
 * feed_id: Feed ID
 * search: Search query for article title or content
 * unread_only: Show only unread articles
 *
 * Returns:
 * Paginated list of articles
 */
export const apiV1EndpointsArticlesListArticles = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesListArticlesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiV1EndpointsArticlesListArticlesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/feeds/{feed_id}/articles/",
    ...options,
  });

/**
 * Delete Article
 *
 * Delete an article.
 *
 * Args:
 * article_id: Article ID
 *
 * Returns:
 * Success message
 */
export const apiV1EndpointsArticlesDeleteArticle = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesDeleteArticleData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiV1EndpointsArticlesDeleteArticleResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/articles/{article_id}/",
    ...options,
  });

/**
 * Get Article
 *
 * Get detailed article information with navigation.
 *
 * Args:
 * article_id: Article ID
 * page: Current page number (for navigation context)
 * unread_only: Whether navigation should be in unread-only context
 *
 * Returns:
 * Detailed article with prev/next navigation
 */
export const apiV1EndpointsArticlesGetArticle = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesGetArticleData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiV1EndpointsArticlesGetArticleResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/articles/{article_id}/",
    ...options,
  });

/**
 * Reload Article
 *
 * Reload a single article (refetch content).
 *
 * Args:
 * article_id: Article ID
 *
 * Returns:
 * Reload status
 */
export const apiV1EndpointsArticlesReloadArticle = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesReloadArticleData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsArticlesReloadArticleResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/articles/{article_id}/reload/",
    ...options,
  });

/**
 * Mark Articles Read
 *
 * Mark multiple articles as read or unread.
 *
 * Args:
 * data: Article IDs and read status
 *
 * Returns:
 * Count of articles updated
 */
export const apiV1EndpointsArticlesMarkArticlesRead = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesMarkArticlesReadData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsArticlesMarkArticlesReadResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/articles/mark-read/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Mark Articles Starred
 *
 * Mark multiple articles as starred or unstarred.
 *
 * Args:
 * data: Article IDs and starred status
 *
 * Returns:
 * Count of articles updated
 */
export const apiV1EndpointsArticlesMarkArticlesStarred = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiV1EndpointsArticlesMarkArticlesStarredData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiV1EndpointsArticlesMarkArticlesStarredResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/articles/mark-starred/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Aggregators
 *
 * List all available aggregators.
 *
 * Args:
 * search: Search query for aggregator name
 * type: Filter by type (managed, social, custom)
 *
 * Returns:
 * List of available aggregators
 */
export const apiV1EndpointsAggregatorsListAggregators = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiV1EndpointsAggregatorsListAggregatorsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiV1EndpointsAggregatorsListAggregatorsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/aggregators/",
    ...options,
  });

/**
 * List Aggregators Grouped
 *
 * List all available aggregators grouped by type.
 *
 * Returns:
 * Aggregators grouped by type (managed, social, custom)
 */
export const apiV1EndpointsAggregatorsListAggregatorsGrouped = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ApiV1EndpointsAggregatorsListAggregatorsGroupedData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    ApiV1EndpointsAggregatorsListAggregatorsGroupedResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/aggregators/grouped/",
    ...options,
  });

/**
 * Get Statistics
 *
 * Get dashboard statistics for the current user.
 *
 * Returns:
 * Statistics including feed counts, article counts, and read percentages
 */
export const apiV1EndpointsStatisticsGetStatistics = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiV1EndpointsStatisticsGetStatisticsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiV1EndpointsStatisticsGetStatisticsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/v1/statistics/",
    ...options,
  });
