// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

/**
 * AuthStatusSchema
 *
 * Authentication status response.
 */
export type AuthStatusSchema = {
  /**
   * Authenticated
   */
  authenticated: boolean;
  user?: UserSchema | null;
};

/**
 * UserSchema
 *
 * User information schema.
 */
export type UserSchema = {
  /**
   * Id
   */
  id: number;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Superuser
   */
  is_superuser: boolean;
  /**
   * Is Staff
   */
  is_staff: boolean;
};

/**
 * LoginResponse
 *
 * Login response schema.
 */
export type LoginResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  user?: UserSchema | null;
};

/**
 * LoginRequest
 *
 * Login request schema.
 */
export type LoginRequest = {
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Input
 */
export type Input = {
  /**
   * Page
   */
  page?: number;
};

/**
 * FeedSchema
 *
 * Schema for feed response.
 */
export type FeedSchema = {
  /**
   * Name
   *
   * Name of the feed
   */
  name: string;
  /**
   * Identifier
   *
   * Feed identifier (URL for RSS, subreddit name for Reddit, channel for YouTube)
   */
  identifier: string;
  /**
   * Feed Type
   *
   * Type of feed: article, youtube, podcast, or reddit
   */
  feed_type?: string;
  /**
   * Aggregator
   *
   * Aggregator ID (e.g., 'heise', 'default')
   */
  aggregator: string;
  /**
   * Enabled
   *
   * Whether the feed is enabled
   */
  enabled?: boolean;
  /**
   * Generate Title Image
   *
   * Extract and display header image
   */
  generate_title_image?: boolean;
  /**
   * Add Source Footer
   *
   * Add source link at bottom
   */
  add_source_footer?: boolean;
  /**
   * Skip Duplicates
   *
   * Skip articles with duplicate titles
   */
  skip_duplicates?: boolean;
  /**
   * Use Current Timestamp
   *
   * Use current time instead of RSS feed date
   */
  use_current_timestamp?: boolean;
  /**
   * Daily Post Limit
   *
   * Daily post target: -1=unlimited, 0=disabled, n>0=~n posts/day
   */
  daily_post_limit?: number;
  /**
   * Aggregator Options
   *
   * Configuration options for the aggregator
   */
  aggregator_options?: {
    [key: string]: unknown;
  };
  /**
   * Id
   */
  id: number;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * User Id
   *
   * User who owns this feed
   */
  user_id?: number | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Article Count
   *
   * Number of articles (only in list view)
   */
  article_count?: number | null;
  /**
   * Unread Count
   *
   * Number of unread articles (only in list view)
   */
  unread_count?: number | null;
};

/**
 * PagedFeedSchema
 */
export type PagedFeedSchema = {
  /**
   * Items
   */
  items: Array<FeedSchema>;
  /**
   * Count
   */
  count: number;
};

/**
 * FeedCreateRequest
 *
 * Schema for creating a new feed.
 */
export type FeedCreateRequest = {
  /**
   * Name
   *
   * Name of the feed
   */
  name: string;
  /**
   * Identifier
   *
   * Feed identifier (URL for RSS, subreddit name for Reddit, channel for YouTube)
   */
  identifier: string;
  /**
   * Feed Type
   *
   * Type of feed: article, youtube, podcast, or reddit
   */
  feed_type?: string;
  /**
   * Aggregator
   *
   * Aggregator ID (e.g., 'heise', 'default')
   */
  aggregator: string;
  /**
   * Enabled
   *
   * Whether the feed is enabled
   */
  enabled?: boolean;
  /**
   * Generate Title Image
   *
   * Extract and display header image
   */
  generate_title_image?: boolean;
  /**
   * Add Source Footer
   *
   * Add source link at bottom
   */
  add_source_footer?: boolean;
  /**
   * Skip Duplicates
   *
   * Skip articles with duplicate titles
   */
  skip_duplicates?: boolean;
  /**
   * Use Current Timestamp
   *
   * Use current time instead of RSS feed date
   */
  use_current_timestamp?: boolean;
  /**
   * Daily Post Limit
   *
   * Daily post target: -1=unlimited, 0=disabled, n>0=~n posts/day
   */
  daily_post_limit?: number;
  /**
   * Aggregator Options
   *
   * Configuration options for the aggregator
   */
  aggregator_options?: {
    [key: string]: unknown;
  };
  /**
   * Icon
   *
   * Feed icon URL
   */
  icon?: string | null;
};

/**
 * FeedDetailSchema
 *
 * Schema for detailed feed view with additional metadata.
 */
export type FeedDetailSchema = {
  /**
   * Name
   *
   * Name of the feed
   */
  name: string;
  /**
   * Identifier
   *
   * Feed identifier (URL for RSS, subreddit name for Reddit, channel for YouTube)
   */
  identifier: string;
  /**
   * Feed Type
   *
   * Type of feed: article, youtube, podcast, or reddit
   */
  feed_type?: string;
  /**
   * Aggregator
   *
   * Aggregator ID (e.g., 'heise', 'default')
   */
  aggregator: string;
  /**
   * Enabled
   *
   * Whether the feed is enabled
   */
  enabled?: boolean;
  /**
   * Generate Title Image
   *
   * Extract and display header image
   */
  generate_title_image?: boolean;
  /**
   * Add Source Footer
   *
   * Add source link at bottom
   */
  add_source_footer?: boolean;
  /**
   * Skip Duplicates
   *
   * Skip articles with duplicate titles
   */
  skip_duplicates?: boolean;
  /**
   * Use Current Timestamp
   *
   * Use current time instead of RSS feed date
   */
  use_current_timestamp?: boolean;
  /**
   * Daily Post Limit
   *
   * Daily post target: -1=unlimited, 0=disabled, n>0=~n posts/day
   */
  daily_post_limit?: number;
  /**
   * Aggregator Options
   *
   * Configuration options for the aggregator
   */
  aggregator_options?: {
    [key: string]: unknown;
  };
  /**
   * Id
   */
  id: number;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * User Id
   *
   * User who owns this feed
   */
  user_id?: number | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Article Count
   *
   * Number of articles (only in list view)
   */
  article_count?: number | null;
  /**
   * Unread Count
   *
   * Number of unread articles (only in list view)
   */
  unread_count?: number | null;
  /**
   * Example
   *
   * Example article HTML for reference
   */
  example?: string | null;
  /**
   * Aggregator Metadata
   *
   * Metadata from the aggregator
   */
  aggregator_metadata?: {
    [key: string]: unknown;
  } | null;
};

/**
 * FeedUpdateRequest
 *
 * Schema for updating an existing feed.
 */
export type FeedUpdateRequest = {
  /**
   * Name
   *
   * Name of the feed
   */
  name?: string | null;
  /**
   * Enabled
   *
   * Whether the feed is enabled
   */
  enabled?: boolean | null;
  /**
   * Generate Title Image
   *
   * Extract and display header image
   */
  generate_title_image?: boolean | null;
  /**
   * Add Source Footer
   *
   * Add source link at bottom
   */
  add_source_footer?: boolean | null;
  /**
   * Skip Duplicates
   *
   * Skip articles with duplicate titles
   */
  skip_duplicates?: boolean | null;
  /**
   * Use Current Timestamp
   *
   * Use current time instead of RSS feed date
   */
  use_current_timestamp?: boolean | null;
  /**
   * Daily Post Limit
   *
   * Daily post target: -1=unlimited, 0=disabled, n>0=~n posts/day
   */
  daily_post_limit?: number | null;
  /**
   * Aggregator Options
   *
   * Configuration options for the aggregator
   */
  aggregator_options?: {
    [key: string]: unknown;
  } | null;
  /**
   * Icon
   *
   * Feed icon URL
   */
  icon?: string | null;
};

/**
 * FeedOperationResponse
 *
 * Generic response for feed operations.
 */
export type FeedOperationResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Feed Id
   */
  feed_id?: number | null;
};

/**
 * FeedReloadResponse
 *
 * Response for feed reload operation.
 */
export type FeedReloadResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Articles Added
   */
  articles_added: number;
  /**
   * Articles Updated
   */
  articles_updated: number;
  /**
   * Articles Skipped
   */
  articles_skipped: number;
  /**
   * Errors
   */
  errors?: Array<string>;
};

/**
 * ArticleListItemSchema
 *
 * Schema for article in list view (minimal fields).
 */
export type ArticleListItemSchema = {
  /**
   * Id
   */
  id: number;
  /**
   * Feed Id
   */
  feed_id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Url
   */
  url: string;
  /**
   * Date
   */
  date: string;
  /**
   * Author
   */
  author?: string | null;
  /**
   * Thumbnail Url
   */
  thumbnail_url?: string | null;
  /**
   * Duration Formatted
   */
  duration_formatted?: string | null;
  /**
   * View Count
   */
  view_count?: number | null;
  /**
   * Score
   */
  score?: number | null;
  /**
   * Is Video
   */
  is_video?: boolean;
  /**
   * Is Podcast
   */
  is_podcast?: boolean;
  /**
   * Is Reddit
   */
  is_reddit?: boolean;
  /**
   * Is Read
   */
  is_read?: boolean;
  /**
   * Is Starred
   */
  is_starred?: boolean;
};

/**
 * PagedArticleListItemSchema
 */
export type PagedArticleListItemSchema = {
  /**
   * Items
   */
  items: Array<ArticleListItemSchema>;
  /**
   * Count
   */
  count: number;
};

/**
 * ArticleDetailSchema
 *
 * Schema for detailed article view with navigation.
 */
export type ArticleDetailSchema = {
  /**
   * Id
   */
  id: number;
  /**
   * Feed Id
   *
   * ID of the feed this article belongs to
   */
  feed_id: number;
  /**
   * Name
   *
   * Article title
   */
  name: string;
  /**
   * Url
   *
   * Article URL
   */
  url: string;
  /**
   * Date
   *
   * Publication date
   */
  date: string;
  /**
   * Content
   *
   * Article HTML content
   */
  content: string;
  /**
   * Thumbnail Url
   *
   * Thumbnail/preview image URL
   */
  thumbnail_url?: string | null;
  /**
   * Media Url
   *
   * Direct URL to media
   */
  media_url?: string | null;
  /**
   * Duration
   *
   * Duration in seconds
   */
  duration?: number | null;
  /**
   * View Count
   *
   * View count (YouTube)
   */
  view_count?: number | null;
  /**
   * Media Type
   *
   * MIME type of media
   */
  media_type?: string | null;
  /**
   * Author
   *
   * Author/creator name
   */
  author?: string | null;
  /**
   * External Id
   *
   * External platform ID
   */
  external_id?: string | null;
  /**
   * Score
   *
   * Score/rating (Reddit upvotes)
   */
  score?: number | null;
  /**
   * Is Video
   *
   * Is this a video (YouTube)
   */
  is_video?: boolean;
  /**
   * Is Podcast
   *
   * Is this a podcast episode
   */
  is_podcast?: boolean;
  /**
   * Is Reddit
   *
   * Is this a Reddit post
   */
  is_reddit?: boolean;
  /**
   * Has Media
   *
   * Has embedded media
   */
  has_media?: boolean;
  /**
   * Duration Formatted
   *
   * Formatted duration
   */
  duration_formatted?: string | null;
  /**
   * Is Read
   *
   * Is this article read by current user
   */
  is_read?: boolean;
  /**
   * Is Starred
   *
   * Is this article starred by current user
   */
  is_starred?: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
  /**
   * Feed Name
   *
   * Name of the feed
   */
  feed_name: string;
  /**
   * Feed Icon
   *
   * Feed icon URL
   */
  feed_icon?: string | null;
  /**
   * Prev Article Id
   *
   * Previous article ID
   */
  prev_article_id?: number | null;
  /**
   * Next Article Id
   *
   * Next article ID
   */
  next_article_id?: number | null;
};

/**
 * ArticleOperationResponse
 *
 * Generic response for article operations.
 */
export type ArticleOperationResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Article Id
   */
  article_id?: number | null;
};

/**
 * ArticleReloadResponse
 *
 * Response for article reload operation.
 */
export type ArticleReloadResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Updated
   */
  updated: boolean;
};

/**
 * BulkOperationResponse
 *
 * Response for bulk operations.
 */
export type BulkOperationResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Message
   */
  message: string;
  /**
   * Count
   */
  count: number;
};

/**
 * MarkReadRequest
 *
 * Request to mark articles as read/unread.
 */
export type MarkReadRequest = {
  /**
   * Article Ids
   */
  article_ids: Array<number>;
  /**
   * Is Read
   */
  is_read?: boolean;
};

/**
 * MarkStarredRequest
 *
 * Request to mark articles as starred/unstarred.
 */
export type MarkStarredRequest = {
  /**
   * Article Ids
   */
  article_ids: Array<number>;
  /**
   * Is Starred
   */
  is_starred?: boolean;
};

/**
 * AggregatorSchema
 *
 * Schema for aggregator information.
 */
export type AggregatorSchema = {
  /**
   * Id
   *
   * Aggregator ID (e.g., 'heise', 'full_website')
   */
  id: string;
  /**
   * Name
   *
   * Human-readable name
   */
  name: string;
  /**
   * Type
   *
   * Aggregator type: managed, custom, or social
   */
  type: string;
  /**
   * Description
   *
   * Description of the aggregator
   */
  description?: string | null;
  /**
   * Url
   *
   * Default URL for this aggregator
   */
  url?: string | null;
  /**
   * Feed Type
   *
   * Feed type: article, youtube, podcast, or reddit
   */
  feed_type?: string | null;
  /**
   * Enabled
   *
   * Whether this aggregator is available
   */
  enabled?: boolean;
};

/**
 * AggregatorListSchema
 *
 * Schema for grouped aggregator list.
 */
export type AggregatorListSchema = {
  /**
   * Managed
   *
   * Managed aggregators for specific sites
   */
  managed?: Array<AggregatorSchema>;
  /**
   * Social
   *
   * Social media aggregators
   */
  social?: Array<AggregatorSchema>;
  /**
   * Custom
   *
   * Generic/custom aggregators
   */
  custom?: Array<AggregatorSchema>;
};

/**
 * StatisticsSchema
 *
 * Schema for dashboard statistics.
 */
export type StatisticsSchema = {
  /**
   * Total Feeds
   *
   * Total number of feeds
   */
  total_feeds: number;
  /**
   * Total Articles
   *
   * Total number of articles
   */
  total_articles: number;
  /**
   * Total Unread
   *
   * Total number of unread articles
   */
  total_unread: number;
  /**
   * Read Percentage
   *
   * Percentage of articles read (0-100)
   */
  read_percentage: number;
  /**
   * Article Feeds
   *
   * Number of article feeds
   */
  article_feeds?: number;
  /**
   * Video Feeds
   *
   * Number of YouTube feeds
   */
  video_feeds?: number;
  /**
   * Podcast Feeds
   *
   * Number of podcast feeds
   */
  podcast_feeds?: number;
  /**
   * Reddit Feeds
   *
   * Number of Reddit feeds
   */
  reddit_feeds?: number;
  /**
   * Articles Today
   *
   * Number of articles added today
   */
  articles_today?: number;
  /**
   * Articles This Week
   *
   * Number of articles added this week
   */
  articles_this_week?: number;
};

export type ApiV1EndpointsAuthAuthStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/status/';
};

export type ApiV1EndpointsAuthAuthStatusResponses = {
  /**
   * OK
   */
  200: AuthStatusSchema;
};

export type ApiV1EndpointsAuthAuthStatusResponse =
  ApiV1EndpointsAuthAuthStatusResponses[keyof ApiV1EndpointsAuthAuthStatusResponses];

export type ApiV1EndpointsAuthLoginUserData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login/';
};

export type ApiV1EndpointsAuthLoginUserResponses = {
  /**
   * OK
   */
  200: LoginResponse;
};

export type ApiV1EndpointsAuthLoginUserResponse =
  ApiV1EndpointsAuthLoginUserResponses[keyof ApiV1EndpointsAuthLoginUserResponses];

export type ApiV1EndpointsAuthLogoutUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout/';
};

export type ApiV1EndpointsAuthLogoutUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ApiV1EndpointsFeedsListFeedsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     */
    search?: string | null;
    /**
     * Feed Type
     */
    feed_type?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Page
     */
    page?: number;
  };
  url: '/api/v1/feeds/';
};

export type ApiV1EndpointsFeedsListFeedsResponses = {
  /**
   * OK
   */
  200: PagedFeedSchema;
};

export type ApiV1EndpointsFeedsListFeedsResponse =
  ApiV1EndpointsFeedsListFeedsResponses[keyof ApiV1EndpointsFeedsListFeedsResponses];

export type ApiV1EndpointsFeedsCreateFeedData = {
  body: FeedCreateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/feeds/';
};

export type ApiV1EndpointsFeedsCreateFeedResponses = {
  /**
   * OK
   */
  200: FeedSchema;
};

export type ApiV1EndpointsFeedsCreateFeedResponse =
  ApiV1EndpointsFeedsCreateFeedResponses[keyof ApiV1EndpointsFeedsCreateFeedResponses];

export type ApiV1EndpointsFeedsDeleteFeedData = {
  body?: never;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: never;
  url: '/api/v1/feeds/{feed_id}/';
};

export type ApiV1EndpointsFeedsDeleteFeedResponses = {
  /**
   * OK
   */
  200: FeedOperationResponse;
};

export type ApiV1EndpointsFeedsDeleteFeedResponse =
  ApiV1EndpointsFeedsDeleteFeedResponses[keyof ApiV1EndpointsFeedsDeleteFeedResponses];

export type ApiV1EndpointsFeedsGetFeedData = {
  body?: never;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: never;
  url: '/api/v1/feeds/{feed_id}/';
};

export type ApiV1EndpointsFeedsGetFeedResponses = {
  /**
   * OK
   */
  200: FeedDetailSchema;
};

export type ApiV1EndpointsFeedsGetFeedResponse =
  ApiV1EndpointsFeedsGetFeedResponses[keyof ApiV1EndpointsFeedsGetFeedResponses];

export type ApiV1EndpointsFeedsUpdateFeedData = {
  body: FeedUpdateRequest;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: never;
  url: '/api/v1/feeds/{feed_id}/';
};

export type ApiV1EndpointsFeedsUpdateFeedResponses = {
  /**
   * OK
   */
  200: FeedSchema;
};

export type ApiV1EndpointsFeedsUpdateFeedResponse =
  ApiV1EndpointsFeedsUpdateFeedResponses[keyof ApiV1EndpointsFeedsUpdateFeedResponses];

export type ApiV1EndpointsFeedsReloadFeedData = {
  body?: never;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: {
    /**
     * Force
     */
    force?: boolean;
  };
  url: '/api/v1/feeds/{feed_id}/reload/';
};

export type ApiV1EndpointsFeedsReloadFeedResponses = {
  /**
   * OK
   */
  200: FeedReloadResponse;
};

export type ApiV1EndpointsFeedsReloadFeedResponse =
  ApiV1EndpointsFeedsReloadFeedResponses[keyof ApiV1EndpointsFeedsReloadFeedResponses];

export type ApiV1EndpointsFeedsClearFeedData = {
  body?: never;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: never;
  url: '/api/v1/feeds/{feed_id}/clear/';
};

export type ApiV1EndpointsFeedsClearFeedResponses = {
  /**
   * OK
   */
  200: FeedOperationResponse;
};

export type ApiV1EndpointsFeedsClearFeedResponse =
  ApiV1EndpointsFeedsClearFeedResponses[keyof ApiV1EndpointsFeedsClearFeedResponses];

export type ApiV1EndpointsArticlesListArticlesData = {
  body?: never;
  path: {
    /**
     * Feed Id
     */
    feed_id: number;
  };
  query?: {
    /**
     * Search
     */
    search?: string | null;
    /**
     * Unread Only
     */
    unread_only?: boolean;
    /**
     * Page
     */
    page?: number;
  };
  url: '/api/v1/feeds/{feed_id}/articles/';
};

export type ApiV1EndpointsArticlesListArticlesResponses = {
  /**
   * OK
   */
  200: PagedArticleListItemSchema;
};

export type ApiV1EndpointsArticlesListArticlesResponse =
  ApiV1EndpointsArticlesListArticlesResponses[keyof ApiV1EndpointsArticlesListArticlesResponses];

export type ApiV1EndpointsArticlesDeleteArticleData = {
  body?: never;
  path: {
    /**
     * Article Id
     */
    article_id: number;
  };
  query?: never;
  url: '/api/v1/articles/{article_id}/';
};

export type ApiV1EndpointsArticlesDeleteArticleResponses = {
  /**
   * OK
   */
  200: ArticleOperationResponse;
};

export type ApiV1EndpointsArticlesDeleteArticleResponse =
  ApiV1EndpointsArticlesDeleteArticleResponses[keyof ApiV1EndpointsArticlesDeleteArticleResponses];

export type ApiV1EndpointsArticlesGetArticleData = {
  body?: never;
  path: {
    /**
     * Article Id
     */
    article_id: number;
  };
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Unread Only
     */
    unread_only?: boolean;
  };
  url: '/api/v1/articles/{article_id}/';
};

export type ApiV1EndpointsArticlesGetArticleResponses = {
  /**
   * OK
   */
  200: ArticleDetailSchema;
};

export type ApiV1EndpointsArticlesGetArticleResponse =
  ApiV1EndpointsArticlesGetArticleResponses[keyof ApiV1EndpointsArticlesGetArticleResponses];

export type ApiV1EndpointsArticlesReloadArticleData = {
  body?: never;
  path: {
    /**
     * Article Id
     */
    article_id: number;
  };
  query?: never;
  url: '/api/v1/articles/{article_id}/reload/';
};

export type ApiV1EndpointsArticlesReloadArticleResponses = {
  /**
   * OK
   */
  200: ArticleReloadResponse;
};

export type ApiV1EndpointsArticlesReloadArticleResponse =
  ApiV1EndpointsArticlesReloadArticleResponses[keyof ApiV1EndpointsArticlesReloadArticleResponses];

export type ApiV1EndpointsArticlesMarkArticlesReadData = {
  body: MarkReadRequest;
  path?: never;
  query?: never;
  url: '/api/v1/articles/mark-read/';
};

export type ApiV1EndpointsArticlesMarkArticlesReadResponses = {
  /**
   * OK
   */
  200: BulkOperationResponse;
};

export type ApiV1EndpointsArticlesMarkArticlesReadResponse =
  ApiV1EndpointsArticlesMarkArticlesReadResponses[keyof ApiV1EndpointsArticlesMarkArticlesReadResponses];

export type ApiV1EndpointsArticlesMarkArticlesStarredData = {
  body: MarkStarredRequest;
  path?: never;
  query?: never;
  url: '/api/v1/articles/mark-starred/';
};

export type ApiV1EndpointsArticlesMarkArticlesStarredResponses = {
  /**
   * OK
   */
  200: BulkOperationResponse;
};

export type ApiV1EndpointsArticlesMarkArticlesStarredResponse =
  ApiV1EndpointsArticlesMarkArticlesStarredResponses[keyof ApiV1EndpointsArticlesMarkArticlesStarredResponses];

export type ApiV1EndpointsAggregatorsListAggregatorsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search
     */
    search?: string;
    /**
     * Type
     */
    type?: string;
  };
  url: '/api/v1/aggregators/';
};

export type ApiV1EndpointsAggregatorsListAggregatorsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<AggregatorSchema>;
};

export type ApiV1EndpointsAggregatorsListAggregatorsResponse =
  ApiV1EndpointsAggregatorsListAggregatorsResponses[keyof ApiV1EndpointsAggregatorsListAggregatorsResponses];

export type ApiV1EndpointsAggregatorsListAggregatorsGroupedData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/aggregators/grouped/';
};

export type ApiV1EndpointsAggregatorsListAggregatorsGroupedResponses = {
  /**
   * OK
   */
  200: AggregatorListSchema;
};

export type ApiV1EndpointsAggregatorsListAggregatorsGroupedResponse =
  ApiV1EndpointsAggregatorsListAggregatorsGroupedResponses[keyof ApiV1EndpointsAggregatorsListAggregatorsGroupedResponses];

export type ApiV1EndpointsStatisticsGetStatisticsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/statistics/';
};

export type ApiV1EndpointsStatisticsGetStatisticsResponses = {
  /**
   * OK
   */
  200: StatisticsSchema;
};

export type ApiV1EndpointsStatisticsGetStatisticsResponse =
  ApiV1EndpointsStatisticsGetStatisticsResponses[keyof ApiV1EndpointsStatisticsGetStatisticsResponses];
