# Generated by Django 5.2.8 on 2025-11-18 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the feed", max_length=255),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="RSS feed URL", max_length=500, unique=True
                    ),
                ),
                (
                    "icon",
                    models.URLField(
                        blank=True, help_text="Feed icon URL", max_length=500
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True, help_text="Example article HTML for reference"
                    ),
                ),
                (
                    "aggregator",
                    models.CharField(
                        help_text="Python module path to aggregator function (e.g., 'aggregators.mein_mmo.aggregate')",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feed",
                "verbose_name_plural": "Feeds",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Article title", max_length=500)),
                (
                    "url",
                    models.URLField(
                        help_text="Article URL", max_length=1000, unique=True
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Publication date"
                    ),
                ),
                ("content", models.TextField(help_text="Article HTML content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(
                        help_text="The feed this article belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="core.feed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="core_articl_date_62f03f_idx"),
                    models.Index(
                        fields=["feed", "-date"], name="core_articl_feed_id_adcf60_idx"
                    ),
                ],
            },
        ),
    ]
