# Generated by Django 5.2.8 on 2025-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="aggregator",
            field=models.CharField(
                default="aggregators.default.aggregate",
                help_text="Python module path to aggregator function (e.g., 'aggregators.mein_mmo.aggregate')",
                max_length=255,
            ),
        ),
    ]
