# Generated by Django 5.2.8 on 2025-11-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_feed_aggregator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GReaderAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Authentication token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the token expires (null = never)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this token belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greader_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GReader Auth Token",
                "verbose_name_plural": "GReader Auth Tokens",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the group", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feeds",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Feeds in this group",
                        related_name="groups",
                        to="core.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this group (None = shared)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fever_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["name"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="UserArticleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Whether the article is read"
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(
                        default=False, help_text="Whether the article is saved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article this state belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="core.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this state",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Article State",
                "verbose_name_plural": "User Article States",
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="core_userar_user_id_3a4d6b_idx",
                    ),
                    models.Index(
                        fields=["user", "is_saved"],
                        name="core_userar_user_id_b96b41_idx",
                    ),
                ],
                "unique_together": {("user", "article")},
            },
        ),
    ]
