# Generated by Django 5.2.8 on 2025-11-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_group_greader_and_userstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubReddit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this subreddit feed", max_length=255
                    ),
                ),
                (
                    "subreddit",
                    models.CharField(
                        help_text="Subreddit name (without r/ prefix, e.g., 'python')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.URLField(
                        blank=True, help_text="Subreddit icon URL", max_length=500
                    ),
                ),
                (
                    "post_limit",
                    models.PositiveIntegerField(
                        default=20, help_text="Number of posts to fetch per aggregation"
                    ),
                ),
                (
                    "comment_limit",
                    models.PositiveIntegerField(
                        default=10, help_text="Number of top comments to fetch per post"
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("new", "New"),
                            ("top", "Top"),
                            ("rising", "Rising"),
                        ],
                        default="hot",
                        help_text="How to sort posts when fetching",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SubReddit",
                "verbose_name_plural": "SubReddits",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RedditPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reddit_id",
                    models.CharField(
                        help_text="Reddit's unique post ID", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(help_text="Post title", max_length=500)),
                (
                    "url",
                    models.URLField(help_text="URL to Reddit post", max_length=1000),
                ),
                (
                    "author",
                    models.CharField(help_text="Post author username", max_length=255),
                ),
                ("score", models.IntegerField(default=0, help_text="Post score")),
                ("date", models.DateTimeField(help_text="Post creation date")),
                (
                    "content",
                    models.TextField(help_text="HTML content with post and comments"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subreddit",
                    models.ForeignKey(
                        help_text="The subreddit this post belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.subreddit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reddit Post",
                "verbose_name_plural": "Reddit Posts",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="core_reddit_date_be94e2_idx"),
                    models.Index(
                        fields=["subreddit", "-date"],
                        name="core_reddit_subredd_076e3b_idx",
                    ),
                ],
            },
        ),
    ]
