# Generated by Django 5.2.8 on 2025-11-19
# Migration to remove SubReddit and RedditPost from core app
# (moved to social app)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subreddit_redditpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedditPost',
        ),
        migrations.DeleteModel(
            name='SubReddit',
        ),
    ]
