# Generated by Django 5.2.8 on 2025-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_api_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="enabled",
            field=models.BooleanField(
                default=True, help_text="Whether this feed is enabled for aggregation"
            ),
        ),
    ]
