# Generated by Django 5.2.8 on 2025-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_feed_enabled_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="add_source_footer",
            field=models.BooleanField(
                default=True,
                help_text="Add a source link at the bottom of each article (allows readers to visit original)",
            ),
        ),
        migrations.AddField(
            model_name="feed",
            name="generate_title_image",
            field=models.BooleanField(
                default=True,
                help_text="Extract and display a header image from article content (improves visual appeal)",
            ),
        ),
    ]
