# Generated by Django 5.2.8 on 2025-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_feed_add_source_footer_feed_generate_title_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="add_source_footer",
            field=models.BooleanField(
                default=True,
                help_text="Add a source link at the bottom of each article",
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="generate_title_image",
            field=models.BooleanField(
                default=True,
                help_text="Extract and display a header image from article content",
            ),
        ),
    ]
