# Generated by Django 5.2.8 on 2025-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_feed_add_source_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="aggregator_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration options for the aggregator (JSON format)",
            ),
        ),
    ]
