# Generated by Django 5.2.8 on 2025-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_update_feed_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="daily_post_limit",
            field=models.IntegerField(
                default=50,
                help_text="Daily post target: -1=unlimited, 0=disabled, n>0=~n posts/day distributed evenly",
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="aggregator",
            field=models.CharField(
                default="full_website",
                help_text="Aggregator ID (e.g., 'heise', 'default')",
                max_length=255,
            ),
        ),
    ]
