# Generated by Django 5.2.8 on 2025-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_move_groups_to_feed"),
        ("core", "0012_add_daily_post_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups this feed belongs to",
                related_name="feeds",
                to="api.group",
            ),
        ),
    ]
