# Generated by Django 5.2.8 on 2025-11-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_feed_url_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="skip_duplicates",
            field=models.BooleanField(
                default=True,
                help_text="Skip articles with duplicate titles from the last 7 days",
            ),
        ),
    ]
