# Generated by Django 5.2.8 on 2025-11-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_feed_skip_duplicates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who owns this feed (None = shared feed visible to all)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
