# Generated by Django 5.2.8 on 2025-11-26 14:23

from django.db import migrations


def assign_feeds_to_first_user(apps, schema_editor):
    """
    Assign all existing feeds (with user=NULL) to the first user in the database.

    If no user exists, this is a no-op (feeds remain with user=NULL, visible to all).
    """
    User = apps.get_model("auth", "User")
    Feed = apps.get_model("core", "Feed")

    # Get first user
    first_user = User.objects.order_by("id").first()

    if first_user:
        # Assign all feeds with user=NULL to this user
        feeds_updated = Feed.objects.filter(user__isnull=True).update(user=first_user)
        print(f"Assigned {feeds_updated} existing feeds to user: {first_user.username}")
    else:
        print("No users found - feeds will remain shared (user=NULL)")


def reverse_assignment(apps, schema_editor):
    """
    Reverse the assignment by setting all feeds back to user=NULL.
    """
    Feed = apps.get_model("core", "Feed")
    Feed.objects.all().update(user=None)
    print("Reversed: Set all feeds back to user=NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_user_ownership"),
    ]

    operations = [
        migrations.RunPython(assign_feeds_to_first_user, reverse_assignment),
    ]
