# Generated by Django 5.2.8 on 2025-11-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_assign_existing_feeds_to_first_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'name', 'created_at'], name='core_articl_feed_id_f698d7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'created_at'], name='core_articl_feed_id_24cb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'date', 'id'], name='core_articl_feed_id_ff1c11_idx'),
        ),
    ]
