# Generated by Django 5.2.8 on 2025-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_article_core_articl_feed_id_f698d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='use_current_timestamp',
            field=models.BooleanField(default=True, help_text='Use current time as article timestamp instead of RSS feed date'),
        ),
    ]
