# Generated by Django 5.2.8 on 2025-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_use_current_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='media_type',
            field=models.CharField(blank=True, help_text="MIME type of media (e.g., 'audio/mpeg')", max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='media_url',
            field=models.URLField(blank=True, help_text='Direct URL to media (video embed URL or audio file)', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail/preview image URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, help_text='View count (for YouTube videos)', null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(choices=[('article', 'Article'), ('youtube', 'YouTube'), ('podcast', 'Podcast')], default='article', help_text='Type of feed: article (default), youtube, or podcast', max_length=20),
        ),
    ]
