# Generated by Django 5.2.8 on 2025-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_feed_type_and_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text='Author/creator name (for Reddit posts, podcasts, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='External platform ID (e.g., Reddit post ID, YouTube video ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score/rating (e.g., Reddit upvotes)', null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(choices=[('article', 'Article'), ('youtube', 'YouTube'), ('podcast', 'Podcast'), ('reddit', 'Reddit')], default='article', help_text='Type of feed: article (default), youtube, or podcast', max_length=20),
        ),
    ]
