# Generated by Django 5.2.8 on 2025-12-04 - AI Integration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_url_to_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add AI fields to Feed model
        migrations.AddField(
            model_name='feed',
            name='ai_translate_to',
            field=models.CharField(
                blank=True,
                default='',
                help_text="Target language code (e.g., 'en', 'de', 'es'). Leave empty to disable translation.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='feed',
            name='ai_summarize',
            field=models.BooleanField(
                default=False,
                help_text='Generate AI summary of article content',
            ),
        ),
        migrations.AddField(
            model_name='feed',
            name='ai_custom_prompt',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Custom AI prompt to process article content. Leave empty to disable.',
                max_length=500,
            ),
        ),
        # Add AI fields to Article model
        migrations.AddField(
            model_name='article',
            name='ai_processed',
            field=models.BooleanField(
                default=False,
                help_text='Whether AI processing was applied to this article',
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_error',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Short error message if AI processing failed',
                max_length=500,
            ),
        ),
        # Create UserAIQuota model
        migrations.CreateModel(
            name='UserAIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=200, help_text='Maximum AI requests per day')),
                ('monthly_limit', models.IntegerField(default=2000, help_text='Maximum AI requests per month')),
                ('daily_used', models.IntegerField(default=0, help_text='AI requests used today')),
                ('monthly_used', models.IntegerField(default=0, help_text='AI requests used this month')),
                ('daily_reset_at', models.DateTimeField(help_text='When daily quota resets (UTC midnight)')),
                ('monthly_reset_at', models.DateTimeField(help_text='When monthly quota resets (first of month)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    help_text='User this quota applies to',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ai_quota',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'User AI Quota',
                'verbose_name_plural': 'User AI Quotas',
            },
        ),
    ]
