# Generated by Django 5.2.8 on 2025-12-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_ai_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='icon',
            field=models.URLField(blank=True, help_text='Feed icon URL', max_length=500, null=True),
        ),
    ]
