"""
Django settings for yana project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Environment variables are loaded from .env file using django-environ.
See .env.example for all available settings.
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ with defaults
# All settings have sensible defaults and can be overridden via .env file
env = environ.Env(
    # Security
    DEBUG=(bool, True),
    SECRET_KEY=(str, "django-insecure-l4x)1=)q58u$0#n^r1pgnt29y)-k%z2y(0h0tud&3)4533!ikb"),
    # Network
    ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
    BASE_URL=(str, "http://localhost:8000"),
    # Database
    DATABASE_ENGINE=(str, "django.db.backends.sqlite3"),
    # Internationalization
    TIME_ZONE=(str, "UTC"),
)

# Read environment file (.env) if it exists
# Variables in .env override defaults above
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = [host.strip() for host in env("ALLOWED_HOSTS").split(",")]

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = [
    f"https://{host.strip()}" for host in env("ALLOWED_HOSTS").split(",") if host.strip() != "*"
]
# Support for proxies
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Secure cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

BASE_URL = env("BASE_URL").rstrip("/")


# Application definition

INSTALLED_APPS = [
    "dal",  # django-autocomplete-light (must be before admin)
    "dal_select2",  # django-autocomplete-light with Select2 (must be before admin)
    "core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_q",  # Background tasks (supervisor manages qcluster in Docker)
    "djangoql",
    "import_export",  # Model-level data import and export
]

# Django Import Export Configuration
# https://django-import-export.readthedocs.io/en/stable/configuration.html
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "yana.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "yana.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Using optimized SQLite backend with performance PRAGMA settings:
# - WAL mode for better concurrency
# - Increased cache size (64MB)
# - Memory-mapped I/O (256MB)
# - Optimized synchronous mode
# See core/db/backends.py for details

DATABASES = {
    "default": {
        "ENGINE": "core.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            # Connection timeout in seconds (prevents "database is locked" errors)
            "timeout": 30,
            # Check same thread (set to False for better performance in multi-threaded apps)
            # Note: Django Q2 uses multiple threads, so we set this to False
            "check_same_thread": False,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django Q2 Configuration
# https://django-q2.readthedocs.io/en/stable/configure.html

Q_CLUSTER = {
    "name": "yana",
    "workers": 4,
    "recycle": 500,
    "timeout": 300,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "redis": None,  # Use ORM broker (database) instead of Redis
    "orm": "default",  # Use the default database connection
    "retry": 360,  # Retry failed tasks for 6 minutes
    "max_attempts": 3,  # Maximum retry attempts
    "ack_failures": True,  # Acknowledge failed tasks
    "sync": False,  # Run asynchronously (set to True for testing)
}
