default_platform(:ios)

platform :ios do
  desc "Generate App Store screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "YanaUITests")
    frame_screenshots(path: "./fastlane/screenshots")
  end
end
