# Generated by Django 5.2.8 on 2025-11-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userarticlestate",
            new_name="api_userart_user_id_47e2b5_idx",
            old_name="core_userar_user_id_3a4d6b_idx",
        ),
        migrations.RenameIndex(
            model_name="userarticlestate",
            new_name="api_userart_user_id_1a69c6_idx",
            old_name="core_userar_user_id_b96b41_idx",
        ),
        # Note: subreddits field removed from Group model - social app no longer exists
    ]
