# Generated by Django 5.2.8 on 2025-11-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_subreddits_to_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="feeds",
        ),
    ]
