# Generated by Django 5.2.8 on 2025-11-28 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_move_groups_to_feed'),
        ('core', '0018_article_core_articl_feed_id_f698d7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userarticlestate',
            index=models.Index(fields=['user', 'article', 'is_read'], name='api_userart_user_id_b2cabe_idx'),
        ),
    ]
