# Generated by Django 5.2.8 on 2025-11-28 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userarticlestate_api_userart_user_id_b2cabe_idx'),
        ('core', '0022_rename_url_to_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userarticlestate',
            index=models.Index(fields=['user', 'is_read', 'article'], name='api_userart_user_id_73c847_idx'),
        ),
    ]
