/**
 * Worker entry point (compiled from worker.ts).
 *
 * This file will be generated by TypeScript compilation.
 * For now, it's a placeholder that will be replaced.
 */

// This will be compiled from worker.ts
require('./worker');
