"""
Django settings for yana project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, []),
    DATABASE_URL=(str, f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
    SECRET_KEY=(str, "django-insecure-change-this-in-production"),
    TIME_ZONE=(str, "Europe/Berlin"),
    LANGUAGE_CODE=(str, "en-us"),
    BASE_URL=(
        str,
        "",
    ),  # Base URL for the site (e.g., https://yana.da-krug.de). If empty, will be constructed from ALLOWED_HOSTS.
    AGGREGATION_SCHEDULE=(str, "*/30 * * * *"),  # Every 30 minutes by default
    AGGREGATION_WORKERS=(int, 4),  # Number of parallel workers for aggregation
    Q_CLUSTER_WORKERS=(int, 2),
    Q_CLUSTER_TIMEOUT=(int, 720),
    Q_CLUSTER_RETRY=(int, 780),
    # AI Integration Settings
    OPENAI_API_URL=(str, "https://api.openai.com/v1"),
    OPENAI_API_KEY=(str, ""),
    AI_MODEL=(str, "gpt-4o-mini"),
    AI_TEMPERATURE=(float, 0.3),
    AI_MAX_TOKENS=(int, 2000),
    AI_DEFAULT_DAILY_LIMIT=(int, 200),
    AI_DEFAULT_MONTHLY_LIMIT=(int, 2000),
    AI_MAX_PROMPT_LENGTH=(int, 500),
    AI_REQUEST_TIMEOUT=(int, 30),
    AI_MAX_RETRIES=(int, 3),
    AI_RETRY_DELAY=(int, 2),
)

# Read .env file if it exists
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")
# Add localhost:4200 for Angular dev server in development
if DEBUG and "http://localhost:4200" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append("http://localhost:4200")

# CSRF cookie settings for API authentication
# Allow JavaScript to read CSRF token from cookies
CSRF_COOKIE_HTTPONLY = False
# Use same-site cookie policy for cross-origin requests in development
CSRF_COOKIE_SAMESITE = "Lax"

# Session cookie settings for authentication persistence
# Ensure session cookies persist across page reloads
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access for security
SESSION_COOKIE_SECURE = not DEBUG  # Only use secure cookies in production (HTTPS)
SESSION_COOKIE_AGE = 1209600  # 2 weeks (default Django value)
SESSION_SAVE_EVERY_REQUEST = False  # Only save session when modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist session across browser restarts

# Base URL for the site (used for generating absolute URLs)
# If not set, will be constructed from ALLOWED_HOSTS (first non-wildcard host)
BASE_URL = env("BASE_URL")
if not BASE_URL and ALLOWED_HOSTS and ALLOWED_HOSTS != ["*"]:
    # Use first non-wildcard host from ALLOWED_HOSTS
    first_host = next((h for h in ALLOWED_HOSTS if h != "*"), None)
    if first_host:
        # Default to https, but can be overridden by setting BASE_URL explicitly
        BASE_URL = f"https://{first_host}"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django_q",
    "djangoql",
    "core",
    "api",
]

MIDDLEWARE = [
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aggregato.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aggregato.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": env.db("DATABASE_URL")}

# Apply SQLite optimizations when using SQLite
# Based on: https://gcollazo.com/optimal-sqlite-settings-for-django/
if DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    DATABASES["default"]["OPTIONS"] = {
        # Use IMMEDIATE transactions to avoid "database is locked" errors
        # when upgrading read locks to write locks
        "transaction_mode": "IMMEDIATE",
        # Timeout in seconds for acquiring a lock
        "timeout": 5,
        # PRAGMA settings for optimal performance
        "init_command": """
            PRAGMA journal_mode = WAL;
            PRAGMA synchronous = NORMAL;
            PRAGMA mmap_size = 134217728;
            PRAGMA journal_size_limit = 67108864;
            PRAGMA cache_size = 2000;
        """,
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Login settings
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE")

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Angular builds with baseHref="/static/" so all assets are under /static/ prefix
# Include Angular build output in staticfiles to be collected
STATICFILES_DIRS = [
    BASE_DIR.parent / "frontend" / "dist" / "browser",
]

# Use simpler storage backend for tests (no manifest required)
if "test" in sys.argv:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            # Use CompressedStaticFilesStorage without Manifest
            # Angular already provides hashed filenames, so we don't need Django's manifest system
            # This storage will compress files (gzip/brotli) but won't add additional hashing
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env("DJANGO_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
        "yana": {
            "handlers": ["console"],
            "level": env("APP_LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}

# Aggregation settings
AGGREGATION_SCHEDULE = env("AGGREGATION_SCHEDULE")
AGGREGATION_WORKERS = env("AGGREGATION_WORKERS")

# Reddit API settings
REDDIT_CLIENT_ID = env("REDDIT_CLIENT_ID", default="")
REDDIT_CLIENT_SECRET = env("REDDIT_CLIENT_SECRET", default="")
REDDIT_USER_AGENT = env("REDDIT_USER_AGENT", default="Yana/1.0")

# YouTube API settings
YOUTUBE_API_KEY = env("YOUTUBE_API_KEY", default="")

# AI Integration settings
OPENAI_API_URL = env("OPENAI_API_URL")
OPENAI_API_KEY = env("OPENAI_API_KEY")
AI_MODEL = env("AI_MODEL")
AI_TEMPERATURE = env("AI_TEMPERATURE")
AI_MAX_TOKENS = env("AI_MAX_TOKENS")
AI_DEFAULT_DAILY_LIMIT = env("AI_DEFAULT_DAILY_LIMIT")
AI_DEFAULT_MONTHLY_LIMIT = env("AI_DEFAULT_MONTHLY_LIMIT")
AI_MAX_PROMPT_LENGTH = env("AI_MAX_PROMPT_LENGTH")
AI_REQUEST_TIMEOUT = env("AI_REQUEST_TIMEOUT")
AI_MAX_RETRIES = env("AI_MAX_RETRIES")
AI_RETRY_DELAY = env("AI_RETRY_DELAY")

# Helper to check if AI is enabled
AI_ENABLED = bool(OPENAI_API_KEY)

# Django-Q2 configuration
Q_CLUSTER = {
    "name": "yana",
    "workers": env("Q_CLUSTER_WORKERS"),
    "timeout": env("Q_CLUSTER_TIMEOUT"),
    "retry": env("Q_CLUSTER_RETRY"),
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "ack_failures": True,
    "max_attempts": 1,
    "attempt_count": 1,
}

# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "yana-cache",
        "TIMEOUT": 300,  # 5 minutes default timeout
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}
